// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0VOZZ1_JqxPcOn2SHgY-9UOehPN_KpAs',
    appId: '1:105139890148:web:16880c6d900f1cf32509f1',
    messagingSenderId: '105139890148',
    projectId: 'volunteervibes-n2vb5',
    authDomain: 'volunteervibes-n2vb5.firebaseapp.com',
    storageBucket: 'volunteervibes-n2vb5.appspot.com',
    measurementId: 'G-K2PWLG6C07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2x_qAVK3ilZDn1BCyKVCG-8qz7w25u1E',
    appId: '1:105139890148:android:c870b2a709e9c1a22509f1',
    messagingSenderId: '105139890148',
    projectId: 'volunteervibes-n2vb5',
    storageBucket: 'volunteervibes-n2vb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkA1TY5Sl5bJ5011Wr22RuawltQdJ96Ps',
    appId: '1:105139890148:ios:3e02d2e6127e16712509f1',
    messagingSenderId: '105139890148',
    projectId: 'volunteervibes-n2vb5',
    storageBucket: 'volunteervibes-n2vb5.appspot.com',
    androidClientId: '105139890148-3j4lq12ooidt68uir22i6lgfmapuqgd4.apps.googleusercontent.com',
    iosClientId: '105139890148-pnb4amnrt904dve5f6a3i7sa1jtpd3hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunteerVibes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkA1TY5Sl5bJ5011Wr22RuawltQdJ96Ps',
    appId: '1:105139890148:ios:8817cb69f0f92a652509f1',
    messagingSenderId: '105139890148',
    projectId: 'volunteervibes-n2vb5',
    storageBucket: 'volunteervibes-n2vb5.appspot.com',
    androidClientId: '105139890148-3j4lq12ooidt68uir22i6lgfmapuqgd4.apps.googleusercontent.com',
    iosClientId: '105139890148-ljna9huvhfqb1bvdiie6gfc7r51c178c.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunteerVibes.RunnerTests',
  );
}
